### PR TITLE
feat: extend suite test coverage to further `bootstrap` contract elements - equal shape as origial series, `test_ratio`, number of bootstraps

### PR DESCRIPTION
**Pull request by fkiraly**
This PR adds test coverage for additional contract elements of `bootstrap`:

* bootstraps must be of equal length as original series
* use of `test_ratio` argument
* number of bootstraps must be equal to `n_boostraps` parameter and `get_n_bootstraps` return

Also improves the test feedback on failure.

As discussed in our workstream meeting today, @astrogilda.

### CODE REVIEW

**Comment by fkiraly** [comment]
Currently fails since `test_size` defaults to 0.2 currently, which is undergoing deprecation until 0.2.0, to change to 0.0.

Options:

* add a `test_size = 0.0` arg to the call
* wait until 0.2.0 to merge this

**Comment by fkiraly** [comment]
how about we cover `test_size` more generally, not just the default?

For this, could you quickly tell me how rounding works? up, down, or to the next integer?

**Comment by astrogilda** [comment]
Rounds down to the nearest integer

**Comment by fkiraly** [comment]
> Rounds down to the nearest integer

Does the test set or the remainig train set round down?

**Pull request merged**
