### PR TITLE
[ENH] boilerplate layer, streamlied extension contract

### PR DESCRIPTION
**Pull request by fkiraly**
This PR streamlines the extension contract for adding more estimators. There are minimal breaking changes, imo these do not require deprecation due to changes affecting only buggy interfaces.

Changes:

* the extension locus for bootstraps is moved to `_bootstrap` and `_get_n_bootstraps` with a clearly documented extension template. These are called from `bootstrap` and `get_n_bootstraps`.
* Repetitive boilerplate code is moved to the space between public and private method.
* Input checking is moved to a single function, and added to `get_n_bootstraps` where it was missing.
* the unused (or buggy) `groups` argument is removed from `get_n_bootstraps`.

### CODE REVIEW

**Comment by fkiraly** [comment]
Q from meeting today: is `X` and `y` necessary in `get_n_bootstraps`? That is, isn't this always identical to the param, `n_bootstraps`?

**Comment by astrogilda** [comment]
Compatibility reasons

**Comment by fkiraly** [comment]
... with ... ?

**Review by astrogilda — APPROVED** [review]

**Comment by astrogilda** [comment]
> ... with ... ?

sorry forgot to respond. compatibility with crossvalidation in sklearn, which has a get_cv method iirc.

**Pull request merged**
