### PR TITLE
added use of uv instead of pip in CI.yml

### LINKED ISSUE #133: use `uv` instead of `pip` in CI.yml
**Is your feature request related to a problem? Please describe.**
speed up installation of packages in CI. we use a matrix of all three OS's, with 5 versions of python, with both soft, and all dependencies -- every second saved counts.

**Describe the solution you'd like**
Use `uv` instead of `pip`.

### PR DESCRIPTION
**Pull request by astrogilda**
# Pull Request Template

## Description

closes #133 

## Type of change

Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by fkiraly** [comment]
hm, that doesn't seem to have worked? It does not find dependencies of the package.

**Comment by astrogilda** [comment]
yep, trying to resolve this.

Best,
Sankalp Gilda, Ph.D.

**Comment by astrogilda** [comment]
Error logs indicate `scikit-learn-extras` has some incompatibility with Python 3.12 on Windows --https://github.com/astrogilda/tsbootstrap/actions/runs/8745910408/job/24001870002?pr=134

Could someone help diagnose? is our only reasonably choice for now to skip testing for this particular combination of python and OS completely and warn the users not to install `tsbootstrap` here until we can verify that sklearn-extras has been appropriately updated?

**Review by fkiraly — CHANGES_REQUESTED** [review]
I'm quite concerned that the `CI.yml` gets much more complicated, and thus harder to maintain... any way around that?

Re the sphinx issu, I am not sure, but the obvious suspects are the lines changed in `conf.py`.

**Comment by astrogilda** [comment]
I thought about ways to simplify the ci file. AFAIK uv requires a virtual
environment, and each run statement essentially opens a new shell,
necessitating activation of the created virtual environment.

**Comment by fkiraly** [comment]
If this is the simplest it can be, then it feels a bit immature and risky to me.
Perhaps later then, when there is a GHA or similar?

**Comment by astrogilda** [comment]
I disagree.. Given the small size of the CI file, I don't really see an issue here. Plus using `uv` instead of `pip` has non-trivially improved the runtimes already.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Happy in-principle to try this out, could we add the "show dependencies" and "show branches" back though? I find that important for debugging.

**Comment by astrogilda** [comment]
Cool, I can do that.

**Comment by astrogilda** [comment]
image

**Pull request merged**
