### PR TITLE
feat: `scikit-base` registry and testing framework

### PR DESCRIPTION
**Pull request by fkiraly**
Depends on https://github.com/astrogilda/tsbootstrap/pull/10 which should be merged first. Implements https://github.com/astrogilda/tsbootstrap/issues/9

Adds `scikit-base` machinery, for `sktime` compatibility.
Contents:

* registry with lookup utility `all_objects`, including tests
* `BaseObject` interface contract test class, `TestAllObjects`
* test scenarios for bootstrap algorithms
* `TestAllBootstraps` a test class specific to bootstrap objects, currently testing input/output contract of the `bootstrap` method
* new tag `capability:multivariate`, which distinguishes boostrap algorithms that can vs cannot handle multivariate data. Used in an informative user facing error message, and matching algorithms with test scenarios.

One open question is, where should tests live?
I added tests currently in a sub-folder of `tsbootstrap` rather than the current `tests` folder, but that's not necessary.

### CODE REVIEW

**Comment by astrogilda** [comment]
> Depends on #10 which should be merged first. Implements #9
> 
> Adds `scikit-base` machinery, for `sktime` compatibility. Contents:
> 
> * registry with lookup utility `all_objects`, including tests
> * `BaseObject` interface contract test class, `TestAllObjects`
> * test scenarios for bootstrap algorithms
> * `TestAllBootstraps` a test class specific to bootstrap objects, currently testing input/output contract of the `bootstrap` method
> 
> One open question is, where should tests live? I added tests currently in a sub-folder of `tsbootstrap` rather than the current `tests` folder, but that's not necessary.

What's the rationale behind changing the location for the tests folder?

**Comment by fkiraly** [comment]
technically, I've added it, not changed it. I just did not know for certain where to put it. No strong opinions where it should go.

**Comment by astrogilda** [comment]
At got it! If you are neutral about it I vote we keep the status quo.

**Comment by fkiraly** [comment]
Sure, feel free to move them around! My main problem right now is that the tests in the classes do not seem to be running, not sure why.

**Comment by astrogilda** [comment]
Wait, do you mean not running, or not passing? In either case, which ones
in particular are you referring to?

**Comment by fkiraly** [comment]
running

**Comment by astrogilda** [comment]
Which ones?

**Comment by fkiraly** [comment]
I think none are running.

Also, what do you mean by status quo: all tests in root `tests` and subfolders, or the status quo within this PR?

**Comment by fkiraly** [comment]
ok, works now, at least from the side of the test framework.

The failures are due to missing default parameter settings, these need to satisfied in one of two ways:

* `sktime` requires default parameter sets to be defined in `get_test_params`, so the test framework can construct instances to test.
* `sklearn` has a partly stricter requirement, that all estimator classes have `__init__` defaults for all parameters (`sktime` does not go that far)

**Comment by astrogilda** [comment]
> ok, works now, at least from the side of the test framework.
> 
> The failures are due to missing default parameter settings, these need to satisfied in one of two ways:
> 
> * `sktime` requires default parameter sets to be defined in `get_test_params`, so the test framework can construct instances to test.
> * `sklearn` has a partly stricter requirement, that all estimator classes have `__init__` defaults for all parameters (`sktime` does not go that far)
> 
> Since we are migrating, the error will come up in test fixture collection, e.g., for `BartlettsBootstrap` not having parameter defaults defined in `get_test_params`. There is also no good way to guess for me, as the bootstrap classes do not have parameters documented clearly.
> 
> My strong recommendation short-to-midterm would be to
> 
> (a) move user facing parameters of any bootstrap class directly to that class, from config. (b) document these clearly in the docstring of the bootstrap class directly, not requiring user to go to the config.
> 
> I would suggest using another PR to fix the issues, and make that either depend on this PR, or have this PR depend on the other, then merge in sequence of dependence. The latter option would avoid merging any failing branch to `main`.

This defeats the whole purpose of the config system -- to write well-separated, cleaner code. Are you saying to merge with sktime this is the only solution?

**Comment by fkiraly** [comment]
> This defeats the whole purpose of the config system -- to write well-separated, cleaner code. Are you saying to merge with sktime this is the only solution?

no, there are two issues in the above.

#### sktime/sklearn compatibility

all this requires is adding default parameter settings for testing, either via `__init__` or `get_test_params` (latter recommended)

More detailed requirements are listed above.

#### usability - by the common user, by power user/extender

not required for integration, but it will make the package harder and somewhat frustrating to use if:

* parameters are specified and documented in locations other than the key objects
* classes are unnecessarily composite

It would be a strong recommendation to move the parameter specification directly into the class it affects.

**Comment by fkiraly** [comment]
opened issue for discussion here: https://github.com/astrogilda/tsbootstrap/issues/43

**Comment by fkiraly** [comment]
added catch to allow `kwargs` in constructors

**Comment by fkiraly** [comment]
failures might be genuine:

* inconsistent return of `bootstrap` method - sometimes generator ("yield"), sometimes list ("return")
* recurring error on default params,
* 
```
>       if not highest_ranked_lags:
>           return aic_ranked_lags[-1]
E           IndexError: index -1 is out of bounds for axis 0 with size 0
```

**Comment by fkiraly** [comment]
2nd one is resolved, the issue was:

* not all bootstrap algorithms accept multivariate input, i.e., shape `(n_inst, n_vars)` with `n_vars>1`.
* the exception that was supposed to be raised was internally silenced (try/except/print, not try/except/raise)

This is solved by:

* adding a tag, and testing dependent on the tag
* moving the multivariate check to `_check_input`

**Comment by fkiraly** [comment]
I've investigated the first issue, and the failure is *not*, as I thought, about generators or not. The problem is that if `return_index=True`, then the return generator produces tuplse of shape

`(list-of[list-of[np.ndarray]], list-of[np.ndarray])`, and it looks like the *second* tuple element is the bootstrapped series, not the first.

Reproducing code:

```python
from tsbootstrap.block_bootstrap import BlackmanBootstrap
from tsbootstrap.tests.scenarios.scenarios_bootstrap import BootstrapUnivarRetIx

# this is the same as running the blackman bootstrap
# with some X, y, and return_indices=True
result_gen = sc.run(boot, method_sequence=["bootstrap"])

result_list = list(result_gen)  # then investigate this list
```

**Pull request merged**
