### PR TITLE
[ENH] test for init signature conventions, simplified `get_n_bootstraps`

### PR DESCRIPTION
**Pull request by fkiraly**
This PR further cleans up logic around the base interface contract, and adds tests.

* the contract tests now check, for all bootstraps, that:
    * `n_bootstraps` is the first parameter, with default 10
    * all parameters have defaults
* `get_n_bootstraps` now always returns `self.n_bootstraps` instead of reaching into the config, i.e., we change an implementation dependent piece of logic to contract dependent logic that always works, thereby removing the need for implementing this again and again for new bootstrap algorithms.

### CODE REVIEW

**Comment by fkiraly** [comment]
I think this PR flags up an open design discussion that we need to close out.

What are our convention on the `n_bootstraps` parameter? I get that every bootstrap algorithm needs to have that. (is that true?)

There are potential conditions we can impose:
A. all parameters must have defaults (sklearn requires this, sktime does not)
B. `n_bootstraps` must be the first parameter
C. `n_bootstraps` always must have the same default, 10

You cannot have not-A, but B and C.

I thought the convention was A and B and C, but there is one bootstrap that does not satisfy it, the `BlockStatisticPreservingBootstrap`.

So either we need to adopt a convention which is not A and B and C, or change the signature of `BlockStatisticPreservingBootstrap`.

**Comment by astrogilda** [comment]
> I think this PR flags up an open design discussion that we need to close out.
> 
> What are our convention on the `n_bootstraps` parameter? I get that every bootstrap algorithm needs to have that. (is that true?)
> 
> There are potential conditions we can impose: A. all parameters must have defaults (sklearn requires this, sktime does not) B. `n_bootstraps` must be the first parameter C. `n_bootstraps` always must have the same default, 10
> 
> You cannot have not-A, but B and C.
> 
> I thought the convention was A and B and C, but there is one bootstrap that does not satisfy it, the `BlockStatisticPreservingBootstrap`.
> 
> So either we need to adopt a convention which is not (A and B and C), or change the signature of `BlockStatisticPreservingBootstrap`.

Good observation. I would prefer we go with the latter -- change the signature of the one errant class.

**Comment by fkiraly** [comment]
to what?

**Comment by astrogilda** [comment]
I was thinking 100?

**Comment by fkiraly** [comment]
I meant, for `block_bootstrap`, not for `n_bootstraps` which already has a default everywhere?

**Pull request merged**
