### PR TITLE
docs: diagnostic attempt to fix sphinx docs

### PR DESCRIPTION
**Pull request by fkiraly**
Trying to fix sphinx docs by using `currentmodule` / `autosummary`

Reated: #7

### CODE REVIEW

**Comment by fkiraly** [comment]
@astrogilda, @benHeid - seems to buid now, but docs CI element fails on warning.

Also, there is no readthedocs build here - this ought to be configured.

**Comment by astrogilda** [comment]
@fkiraly @benHeid do we want to keep this PR or close it? we have fixed the sphinx doc not rendering issue, no?

**Comment by fkiraly** [comment]
are the tables rendering fine now? what was the issue?

**Comment by astrogilda** [comment]
> are the tables rendering fine now? what was the issue?

I think this might have been a duplicate of #7 . What exactly were we trying to solve here?

**Comment by fkiraly** [comment]
not sure, but no need to keep open if you think all is fixed.

I was trying to diagnose the missing estimator pages.

**Comment by astrogilda** [comment]
cool, then i'll close for now

**Comment by astrogilda** [comment]
cool, then i'll close for now

**Pull request closed without merging**
